import fs from 'node:fs/promises';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {Vector3,Raycaster,DoubleSide,Box3} from 'three';
import {CROWN} from '../src/fin-crown.js';
import {createAft} from '../src/aft.js';import {insideHull,logicalX} from '../src/model.js';import {finishedRoofY} from '../src/exterior-profile.js';
const bytes=await fs.readFile('output/leo-interior-v01/leo-exterior.glb');const gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');gltf.scene.traverse(o=>{const a=gltf.parser.associations.get(o);if(a?.nodes!==undefined)o.name=gltf.parser.json.nodes[a.nodes].name||o.name;});gltf.scene.updateMatrixWorld(true);
const wings=[],pods=[],fin=[];gltf.scene.traverse(o=>{if(o.name==='Blended_double_delta')wings.push(o);if(o.name==='Sculpted_nacelle_shell')pods.push(o);if(o.name==='Swept_cat_tail')fin.push(o);});for(const group of [...wings,...pods,...fin])group.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])m.side=DoubleSide;});
const ray=new Raycaster(),up=new Vector3(0,1,0),right=new Vector3(1,0,0),cache=new Map(),roofCache=new Map();
function inSurface(p,objects,axis){const k=axis+':'+(axis==='x'?p.y+','+p.z:p.x+','+p.z)+':'+(objects===fin?'fin':objects===pods?'pod':'wing');let limits=cache.get(k);if(!limits){ray.set(axis==='x'?new Vector3(-400,p.y,p.z):new Vector3(p.x,-100,p.z),axis==='x'?right:up);ray.far=1000;const h=ray.intersectObjects(objects,true).map(h=>axis==='x'?h.point.x:h.point.y);limits=h.length>=2?[Math.min(...h),Math.max(...h)]:[Infinity,-Infinity];cache.set(k,limits);}const v=axis==='x'?p.x:p.y;return v>=limits[0]+.015&&v<=limits[1]-.015;}
function inCrown(p){if(p.y<CROWN.floor-.61||p.y>CROWN.ceiling+.61)return false;let inside=false,d=Infinity;const poly=CROWN.outline;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[j],b=poly[i];if((a[1]>p.z)!==(b[1]>p.z)&&p.x<(b[0]-a[0])*(p.z-a[1])/(b[1]-a[1])+a[0])inside=!inside;const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.z-a[1])*dz)/(dx*dx+dz*dz)));d=Math.min(d,Math.hypot(p.x-a[0]-t*dx,p.z-a[1]-t*dz));}return inside||d<.28;}
function fits(p){if(inCrown(p))return true;if(insideHull(p.x,p.y,p.z)){const k=p.x+','+p.z;if(!roofCache.has(k))roofCache.set(k,finishedRoofY(logicalX(p.x),p.z));if(p.y<=roofCache.get(k))return true;}if(Math.abs(p.z)>90&&inSurface(p,pods,'y'))return true;if(Math.abs(p.z)>20&&inSurface(p,wings,'y'))return true;if(p.y>24&&Math.abs(p.z)<4.5&&inSurface(p,fin,'x'))return true;return false;}
const aft=createAft(),bad=new Map();let samples=0;const checked=new Set();aft.root.traverse(o=>{if(!o.isMesh||o.userData.retainedCap||o.userData.crownClosure)return;const pos=o.geometry.attributes.position;for(let i=0;i<pos.count;i++){const p=new Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld),key=p.toArray().map(v=>v.toFixed(4)).join(',');if(checked.has(key))continue;checked.add(key);samples++;if(!fits(p)&&!bad.has(o.name))bad.set(o.name,p.toArray());}});
console.log({samples,failures:[...bad]});if(bad.size){process.exitCode=1;}else await fs.writeFile('output/leo-interior-v01/aft-fit-report.json',JSON.stringify({status:'PASS',samples,scope:'New geometry inside the usable central hull or actual saved wing, pod and fin meshes, or the explicitly revised panoramic crown envelope. The retained outer cap is verified against the original underside separately in check-polish; the closure skirt is checked by check-crown-closure. Machinery and structure remain conceptual.'},null,2));
